### ISSUE TITLE
Error in hook on debug bar

### ISSUE THREAD

**Issue by madvik** [imath/entrepot#13]
Hi @imath , 
I see it in my debug bar:

> WARNING: wp-includes/class-wp-hook.php:286 - call_user_func_array() expects parameter 1 to be a valid callback, function '000000006df8f046000000000cc9f253render_notices' not found or invalid function name
> include('wp-admin/edit-form-advanced.php'), require_once('wp-admin/admin-header.php'), do_action('in_admin_header'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, entrepot_catch_all_notices, do_action('entrepot_notices'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array

I see this: `do_action('entrepot_notices')` and I think it is a problem of your plugin.

**Comment by imath** [comment]
Hi thanks for your feedback. You certainly have a plugin adding a notice that is encapsulated within a class. Could you look for `function render_notices` in a text editor that allows files search restricting the search to the `/wp-content/plugins` directory to find the plugin(s) so that i can reproduce this ?

**Comment by imath** [comment]
Ok i got it! It will be fixed for the next release.
