### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by lriaudel** [imath/entrepot#7]
Hi,
When we see the plugin list, we can see the plugin to update. But before it is important to see the changelog.
But when we want to read-it , we can click on "View details" and we see this page for exemple :
> wp-admin/plugin-install.php?tab=plugin-information&plugin=wp-statuses&TB_iframe=true&width=600&height=550

We don't can read the changelog on it directly contrary to wp.org.

**Comment by imath** [comment]
Hi,

Thanks for your feedback. @lriaudel what is the "plugin list" for you ?

![changelog](https://user-images.githubusercontent.com/1834524/28269630-08ae5484-6b03-11e7-9176-845fba04c7a5.png)


Because, in the above plugins list, when one of the Entrepôt registered plugin is to be updated (in this example WP Statuses) there's a yellow background with these 2 possible actions:
- View version 1.2.2 details (< this is the changelog)
- or Update now.

If it's in the 'Add Plugins' screen on the Entrepôt tab, then i agree this information is not available, i'll try to figure out a way.

**Comment by lriaudel** [comment]
For me plugin list is : `wp-admin/plugins.php`
I talk about the windows open when I clicked on "view detail".
I don't test update background for the moment.

**Comment by imath** [comment]
> When we see the plugin list, we can see the plugin to **update**. But before it is important to see the changelog.

Then on `wp-admin/plugins.php` the version details will appear when there's an available update.

A changelog with all versions listed is not available, if that's what you're looking for. To make this happen, each plugin should include a CHANGELOG.md into their files. Let's work on it for 1.2 :)

**Comment by madvik** [comment]
Yes it is an enhancement, not a bug report ;-)

**Comment by lriaudel** [comment]
Yes it is an enhancement, not a bug report :-b

**Comment by imath** [comment]
FYI in 1.2.0 it will be possible to add the CHANGELOG and other resources such as:
- a link to the Repository wiki
- a donate link.

The UI will changed a bit to use a split button. See screenshot below:

![split-button](https://user-images.githubusercontent.com/1834524/28638854-7f099946-7246-11e7-97a3-7537d499e3b4.png)
